name: Terraform Infrastructure Deployment

on:
  push:
    branches:
      - feature/terraform-infra

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Debug (VERY IMPORTANT)
      - name: Debug Current Directory
        run: |
          echo "Current Path:"
          pwd
          echo "Listing Files:"
          ls -R

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Terraform Init (ROOT)
      - name: Terraform Init
        run: terraform init

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan (DEV)
      - name: Terraform Plan
        run: terraform plan -var-file=environments/dev.tfvars

      # Terraform Apply (DEV)
      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=environments/dev.tfvars